name: My Sample Build Workflow

on:
  workflow_call:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "build workflow job"
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
